export const FETCH_PLACE_VENUES = 'FETCH_PLACE_VENUES';
export const FETCH_PLACE_VENUES_SUCCESS = 'FETCH_PLACE_VENUES_SUCCESS';
export const FETCH_PLACE_VENUES_ERROR = 'FETCH_PLACE_VENUES_ERROR';

export const SET_PLACE = 'SET_PLACE';
export const CLEAR_VENUES = 'CLEAR_VENUES';
