export const FETCH_PLACES = 'FETCH_PLACES';
export const FETCH_PLACES_SUCCESS = 'FETCH_PLACES_SUCCESS';
export const FETCH_PLACES_ERROR = 'FETCH_PLACES_ERROR';

export const SET_PLACE = 'SET_PLACE';
export const CLEAR_VENUES = 'CLEAR_VENUES';
