export const FETCH_VENUE = 'FETCH_VENUE';
export const FETCH_VENUE_SUCCESS = 'FETCH_VENUE_SUCCESS';
export const FETCH_VENUE_ERROR = 'FETCH_VENUE_ERROR';

export const SET_VENUE = 'SET_VENUE';

export const FETCH_INSTAGRAM = 'FETCH_INSTAGRAM';
export const FETCH_INSTAGRAM_SUCCESS = 'FETCH_INSTAGRAM_SUCCESS';
export const FETCH_INSTAGRAM_ERROR = 'FETCH_INSTAGRAM_ERROR';
